# Generated by Django 5.0.3 on 2024-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("genre", models.CharField(max_length=25)),
                ("availability", models.BooleanField(default=True)),
                ("number_of_copies", models.IntegerField()),
                ("book_number", models.CharField(max_length=25)),
                ("author", models.CharField(max_length=25)),
                ("publisher", models.CharField(max_length=25)),
                ("Language", models.CharField(default="English", max_length=25)),
            ],
        ),
    ]
