# Generated by Django 4.2.11 on 2024-04-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "libraryManagementSystem",
            "0003_remove_borrowedbook_username_borrowedbook_full_name",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("returned_date", models.DateField(auto_now_add=True)),
                (
                    "returned_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryManagementSystem.borrowedbook",
                    ),
                ),
            ],
        ),
    ]
