# Generated by Django 4.2.11 on 2024-04-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0004_returnedbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnedbook",
            name="returned_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryManagementSystem.book",
            ),
        ),
    ]
