# Generated by Django 4.2.11 on 2024-04-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0005_alter_returnedbook_returned_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnedbook",
            name="returned_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryManagementSystem.borrowedbook",
            ),
        ),
    ]
