# Generated by Django 4.2.11 on 2024-04-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0007_alter_borrowedbook_full_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowedbook",
            old_name="full_name",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="returnedbook",
            old_name="full_name",
            new_name="username",
        ),
    ]
