# Generated by Django 4.2.11 on 2024-04-03 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "libraryManagementSystem",
            "0009_borrowbook_alter_returnedbook_returned_book_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("returned", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraryManagementSystem.book",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="returnedbook",
            name="returned_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="libraryManagementSystem.borrowedbook",
            ),
        ),
        migrations.DeleteModel(
            name="BorrowBook",
        ),
    ]
