# Generated by Django 4.2.11 on 2024-04-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "libraryManagementSystem",
            "0010_borrowedbook_alter_returnedbook_returned_book_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedbook",
            name="returned",
        ),
    ]
