# Generated by Django 4.2.11 on 2024-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0011_remove_borrowedbook_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=50),
        ),
    ]
