# Generated by Django 4.2.11 on 2024-04-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0013_overduebook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fine",
        ),
    ]
