# Generated by Django 4.2.11 on 2024-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0015_alter_overduebook_fine_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Language",
            new_name="language",
        ),
        migrations.AlterField(
            model_name="book",
            name="availability",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
    ]
