# Generated by Django 4.2.11 on 2024-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0017_borrowedbook_fine_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="fine_amount",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
