# Generated by Django 4.2.11 on 2024-04-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0018_alter_borrowedbook_fine_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="fine_amount",
            field=models.CharField(default="$10.00 dollars", max_length=50),
        ),
    ]
