# Generated by Django 4.2.11 on 2024-04-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryManagementSystem", "0019_alter_borrowedbook_fine_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OverdueBook",
        ),
    ]
